language: node_js
node_js:
    - 4.2.6
notifications:
    - tec.guilherme.dsc@gmail.com
before_install:
    - npm isntall -g bower
    - npm install -g grunt-cli
    - npm install -g karma-cli
    - npm install -g protractor
    - webdriver-manager update
    - bower install
before_script:
    - grunt
    - cd dist
script:
    - karma start config/karma.config.js --single-run --browsers PhantomJS